# Generated by Django 4.2.2 on 2024-05-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0007_remove_appointment_doctor_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
