# Generated by Django 4.2.2 on 2024-05-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0008_remove_producto_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
