# Generated by Django 4.2.2 on 2024-05-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0009_rename_producto_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id',
        ),
        migrations.AddField(
            model_name='productos',
            name='id_producto',
            field=models.AutoField(db_column='id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
