# Generated by Django 4.2.2 on 2024-05-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0010_remove_productos_id_productos_id_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
