# Generated by Django 4.2.2 on 2024-05-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0011_alter_productos_id_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='descripcion',
        ),
    ]
