# Generated by Django 4.2.2 on 2024-05-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0012_remove_productos_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='articulos',
        ),
    ]
