# Generated by Django 4.2.2 on 2024-05-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0013_rename_productos_articulos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articulos',
            new_name='articulo',
        ),
    ]
