# Generated by Django 4.2.2 on 2024-05-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0014_rename_articulos_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='id_producto',
            new_name='id_articulo',
        ),
    ]
